# Generated by Django 4.0 on 2022-01-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoConqr_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userprofill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=80)),
                ('language', models.CharField(max_length=60)),
                ('level', models.CharField(max_length=45)),
                ('technology', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='followup',
            field=models.CharField(default='null', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.CharField(default=4, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='technology',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
