# Generated by Django 4.0 on 2022-01-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoConqr_dashboard', '0002_userprofill_course_followup_course_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
