# Generated by Django 4.0 on 2022-01-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoConqr_dashboard', '0005_alter_course_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='doc_link',
            field=models.CharField(default='hello', max_length=150),
            preserve_default=False,
        ),
    ]
