# Generated by Django 4.0 on 2022-01-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoConqr_dashboard', '0006_course_doc_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=450),
        ),
    ]
