# Generated by Django 4.0 on 2022-01-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoConqr_dashboard', '0007_alter_course_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofill',
            old_name='first_name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userprofill',
            old_name='last_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='userprofill',
            name='background',
            field=models.CharField(default='no', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofill',
            name='password',
            field=models.CharField(default='yes', max_length=100),
            preserve_default=False,
        ),
    ]
