# Generated by Django 4.0 on 2022-01-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoConqr_dashboard', '0008_rename_first_name_userprofill_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofill',
            name='front',
            field=models.CharField(default='core_html_combo', max_length=100),
            preserve_default=False,
        ),
    ]
