# Generated by Django 4.0 on 2022-01-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoConqr_dashboard', '0009_userprofill_front'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60)),
                ('like', models.CharField(max_length=100)),
                ('dislike', models.CharField(max_length=100)),
                ('suggest', models.CharField(max_length=300)),
                ('imporve', models.CharField(max_length=300)),
            ],
        ),
    ]
