# Generated by Django 4.0 on 2022-01-29 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoConqr_dashboard', '0010_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedback',
            new_name='feedback_a',
        ),
    ]
