# Generated by Django 4.0 on 2022-01-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoConqr_dashboard', '0011_rename_feedback_feedback_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_a',
            name='rate',
            field=models.CharField(default='5', max_length=20),
            preserve_default=False,
        ),
    ]
